### ISSUE TITLE
缺失文件

### ISSUE THREAD

**Issue by jerehrong** [ffhibnese/Model-Inversion-Attack-ToolBox#62]
你好，我在尝试运行您的代码的时候发现一些文件是缺失的，导致代码难以运行，例如在/Model-Inversion-Attack-ToolBox-main/examples/standard/attacks/lokt.py文件中代码相关的路径“checkpoints_v2/attacks/lokt/lokt_celeba64_densenet169_celeba64_ir152.pth”不存在下载你们提供的预训练模型中的文件夹checkpoints_v2/attacks为空。另外在根目录的readme.md文件中提到的checkpoints_structure.txt、attack_scripts、defense_scripts等文件或文件夹是不存在的。如上问题导致代码无法运行

**Comment by ffhibnese** [comment]
你好，感谢关注。
我们正在进行严密文件检查，目前判断应该是漏传了相关文件。稍后我的合作者会进行回复并协助解决问题，谢谢！

**Comment by Chrisqcwx** [comment]
感谢您提交这个Issue并指出这些问题！

+ 关于checkpoints_v2/attacks下的一些GAN和代理模型的权重文件，我们会在几天内进行上传至云盘。
+ 关于checkpoints_structure.txt、attack_scripts、defense_scripts，这是Toolbox v1.0的文件/文件夹，现已经不再需要。目前的示例脚本均在examples/standard中。

我们将在权重文件上传后通知您，如果在此过程中有任何需要的文件或其他疑问，欢迎继续联系我们，谢谢！

**Comment by jerehrong** [comment]
感谢您的回复，刚才我尝试运行Model-Inversion-Attack-ToolBox-main/src/modelinversion/attack/C2FMI/attack.py文件发现其中foldermanager包并不存在。

**Comment by jerehrong** [comment]
我在尝试运行不同攻击的python文件时发现，有许多路径需要自己填充的，但是由于我是第一次接触该领域，导致我并不能正确的填充路径，以至于基本无法使用您提供的代码。希望您可以为每种攻击和防御文件提供详细的使用指导，非常感谢！

**Comment by Chrisqcwx** [comment]
C2FMI 与 DeepInversion 模块位于 Model-Inversion-Attack-ToolBox-main/src/modelinversion/attack/ 文件夹下的相关代码已弃用，现已删除。

我们在 docs/ 文件夹下提供了三份文档，供您参考：

+ dataset.md：介绍数据集的下载方式。
+ path.md：提供路径填写的相关说明。
+ simple_process.md：展示了 GMI 全流程的样例。KED、BREP、Mirror、PPA、IF 和 GMI 的流程基本一致。需要注意的是，Mirror、PPA、IF 这三种方法不需要自行训练 GAN。对于第一次接触的用户，我们建议从 GMI 和 KED 这两个算法开始。其余算法的详细说明我们会在后续逐步补充。

如果您有其它疑问，欢迎随时通过 Issue 或邮箱与我们联系。

**Comment by Chrisqcwx** [comment]
权重文件已上传

**Comment by jerehrong** [comment]
感谢您的回复，我会按照您提供的方法运行代码。

**Comment by jerehrong** [comment]
你好，在datasets.md文件中有多少个执行步骤？你们的文件中提到“For celeba with low resolution, you can directly use your download file above for step 3”，但是文件中只有两个步骤。在训练分类器的时候没有发现可以填写数据集图片路径的地方。    train_dataset_path = 'Model-Inversion-Attack-ToolBox-main/src/checkpoints_v2/dataset/celeba_low/private_train.txt'
test_dataset_path = 'Model-Inversion-Attack-ToolBox-main/src/checkpoints_v2/dataset/celeba_low/private_test.txt'
experiment_dir = 'ir152'
以上是我填写的内容，但是我在运行lokt方法论文提供的代码时发现他的数据集相关路径是这样设置的，其中img_priv_path和img_pub_path为存储图片的路径，train_file_path等为数据集划分的txt文件。在您提供的代码中我并没有发现可以填写数据集图片路径的地方
        "pub_file_path": "./data_files/celeba_ganset.txt",
        "test_file_path": "data_files/celeba_testset.txt",
        "train_file_path": "./data_files/celeba_trainset.txt",
          "img_priv_path": "/datasets/celeba/img_align_celeba/",
        "img_pub_path": "/datasets/celeba/img_align_celeba/",

**Comment by baogiadoan** [comment]
hi, I am facing the same issue, and as I checked the weights in the Google drive, these weight files seems not be there, can you please help to upload those files again? 

```
        /checkpoints_v2.0/attacks/lokt/lokt_celeba64_densenet121_celeba64_ir152.pth',
        /checkpoints_v2.0/attacks/lokt/lokt_celeba64_densenet161_celeba64_ir152.pth',
        /checkpoints_v2.0/attacks/lokt/lokt_celeba64_densenet169_celeba64_ir152.pth',
```

also this:
`checkpoints_v2.0/classifier/celeba112/celeba112_facenet112_97.72.pth`
