### ISSUE TITLE
能否使用其他数据集

### ISSUE THREAD

**Issue by jerehrong** [ffhibnese/Model-Inversion-Attack-ToolBox#64]
你好！我想要使用MNIST,Cifair-10等数据集，请问代码中涉及到模型结构和攻击及评价代码能否支持。是否只需要修改最后一层的num_classes就可以。对实验结果会不会有比较大的影响

**Comment by Chrisqcwx** [comment]
对于数据集，只需要每个item都是image, label的格式即可。使用torchvision提供的就行

对于模型，我们没有提供这两个数据集分辨率对应的模型，可参照src/modelinversion/models/classifiers/classifier64.py中的模型定义，进行自定义模型
1. 在类别前面添加@register_model('<类名别称>')。用于自动保存和加载模型
2. 继承BaseImageClassifier类
3. 在__init__函数前添加@ModelMixin.register_to_config_init。用于自动保存初始化参数
4. 不使用forward函数，改用_forward_impl函数，返回值有两个。第一个是前向传播的最终输出（分类的logit），第二是其它信息的字典，其中'feature'为模型倒数第二层输出，用于评估。故最简单的方法是返回（分类输出的logit, {'feature': 倒数第二层输出}）
