### ISSUE TITLE
运行结果问题

### ISSUE THREAD

**Issue by jerehrong** [ffhibnese/Model-Inversion-Attack-ToolBox#65]
你好我在使用你们提供的被攻击模型和我自己使用celeba64.py训练出来的模型(测试精度为93.298）作为lommagmi.py的被攻击模型时。攻击效果top1为0.3-0.4之间、top5在0.5左右.与论文《Re-thinking Model Inversion Attacks Against Deep Neural Networks》展现的实验结果相差比较大。我想了解一下产生这样的结果是正常的吗？我的设置如下：
gmi.py:     dataset_path = '/Model-Inversion-Attack-ToolBox-main/datasets/celeba/public'   experiment_dir = '/Model-Inversion-Attack-ToolBox-main/GAN/model/gmi'
lomma.py:
    generator_ckpt_path = '/Model-Inversion-Attack-ToolBox-main/GAN/model/gmi/G.pth'  # '/data/yuhongyao/papar_codes/PLG-MI-Attack/plgsmalltest/gen_latest.pth.tar'
    discriminator_ckpt_path = '/Model-Inversion-Attack-ToolBox-main/GAN/model/gmi/D.pth'
    eval_model_ckpt_path = (
        '/Model-Inversion-Attack-ToolBox-main/MIA_box/checkpoints_v2.0/classifier/celeba112/celeba112_facenet112_97.72.pth'
    )
    aug_model_efficientnet_b0_path = '/Model-Inversion-Attack-ToolBox-main/MIA_box/checkpoints_v2.0/attacks/lomma/lomma_celeba64_efficientnet_b0_celeba64_ir152.pth'
    aug_model_efficientnet_b1_path = '/Model-Inversion-Attack-ToolBox-main/MIA_box/checkpoints_v2.0/attacks/lomma/lomma_celeba64_efficientnet_b1_celeba64_ir152.pth'
    aug_model_efficientnet_b2_path = '/Model-Inversion-Attack-ToolBox-main/MIA_box/checkpoints_v2.0/attacks/lomma/lomma_celeba64_efficientnet_b2_celeba64_ir152.pth'
    public_dataset_path = (
        '/Model-Inversion-Attack-ToolBox-main/datasets/celeba/public'
    )
    eval_dataset_path = '/Model-Inversion-Attack-ToolBox-main/datasets/celeba/private_train'
    
    另外我想要运行使用lomma算法的kedmi是不是可以直接把generator_ckpt_path，discriminator_ckpt_path改为kedmi.py训练出来的生成器和鉴别器的路径
![Snipaste_2024-11-02_15-40-19](https://github.com/user-attachments/assets/c8c08bcc-c725-43ec-9cf3-e25a537c0d93)
![Snipaste_2024-11-02_15-41-13](https://github.com/user-attachments/assets/d3403b4e-eaad-4916-9795-d87562bf1c44)
![Snipaste_2024-11-02_15-42-44](https://github.com/user-attachments/assets/d55191ed-688e-45b1-8ca7-a3dd56f44152)

**Comment by Chrisqcwx** [comment]
模型反演攻击在使用不同模型时的评估指标波动很大，使用不同模型之间的结果不具有太大的可比性。因此，只需要在相同的模型下，比较不同攻击算法评估结果的相对大小，其绝对数值意义不大。

lomma算法只需要使用和GMI / KED相同的GAN即可
