### ISSUE TITLE
cannot find model checkpoints

### ISSUE THREAD

**Issue by baogiadoan** [ffhibnese/Model-Inversion-Attack-ToolBox#66]
@Chrisqcwx hi, I am facing the same issue as #62  , and as I checked the weights in the Google drive, these weight files seems not be there, can you please help to upload those files again?
```
        /checkpoints_v2.0/attacks/lokt/lokt_celeba64_densenet121_celeba64_ir152.pth',
        /checkpoints_v2.0/attacks/lokt/lokt_celeba64_densenet161_celeba64_ir152.pth',
        /checkpoints_v2.0/attacks/lokt/lokt_celeba64_densenet169_celeba64_ir152.pth',
```

also this ckpt is also missing: 
`checkpoints_v2.0/classifier/celeba112/celeba112_facenet112_97.72.pth`

all of these files are important to replicate the `lokt` attack

**Comment by Chrisqcwx** [comment]
Hi! The checkpoints have been uploaded.
